server:
    port: 8082

fiap:
    debug: false

spring:
    datasource:
        url: jdbc:h2:C:/workspace/fiap/workspace/spring;DB_CLOSE_ON_EXIT=FALSE
        username: fiap
        password: fiap
    h2:
        console:
            enabled: true # localhost:8082